CREATE TABLE municipio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, icono VARCHAR(50),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE comercio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL REFERENCES municipio(id),
    categoria_id BIGINT NOT NULL REFERENCES categoria(id),
    nombre VARCHAR(160) NOT NULL, slug VARCHAR(160) NOT NULL,
    descripcion TEXT, direccion VARCHAR(300), codigo_postal VARCHAR(10),
    telefono VARCHAR(30), whatsapp VARCHAR(30), email VARCHAR(254),
    web VARCHAR(2000), instagram VARCHAR(2000), google_maps_url VARCHAR(2000),
    destacado BOOLEAN NOT NULL DEFAULT FALSE, activo BOOLEAN NOT NULL DEFAULT TRUE,
    demo BOOLEAN NOT NULL DEFAULT FALSE,
    verificado BOOLEAN NOT NULL DEFAULT FALSE, fecha_verificacion DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (municipio_id, slug),
    CHECK ((verificado AND fecha_verificacion IS NOT NULL) OR (NOT verificado AND fecha_verificacion IS NULL))
);
CREATE INDEX idx_comercio_categoria ON comercio(categoria_id);
CREATE INDEX idx_comercio_slug ON comercio(slug);
CREATE TABLE horario_comercio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comercio_id BIGINT NOT NULL REFERENCES comercio(id) ON DELETE CASCADE,
    dia_semana SMALLINT NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
    hora_apertura TIME, hora_cierre TIME, cerrado BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK ((cerrado AND hora_apertura IS NULL AND hora_cierre IS NULL) OR
           (NOT cerrado AND hora_apertura IS NOT NULL AND hora_cierre IS NOT NULL))
);
CREATE INDEX idx_horario_comercio ON horario_comercio(comercio_id);
CREATE TABLE imagen_comercio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comercio_id BIGINT NOT NULL REFERENCES comercio(id) ON DELETE CASCADE,
    url VARCHAR(2000) NOT NULL, texto_alternativo VARCHAR(300) NOT NULL, orden INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_imagen_comercio ON imagen_comercio(comercio_id, orden);
CREATE TABLE fuente_comercio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comercio_id BIGINT NOT NULL REFERENCES comercio(id) ON DELETE CASCADE,
    tipo_fuente VARCHAR(30) NOT NULL CHECK (tipo_fuente IN ('WEB_OFICIAL','AYUNTAMIENTO','GOOGLE_MAPS','RED_SOCIAL','OTRO')),
    url VARCHAR(2000) NOT NULL, fecha_consulta DATE NOT NULL
);
CREATE INDEX idx_fuente_comercio ON fuente_comercio(comercio_id);

-- Conserva las fechas de auditoría incluso cuando se actualiza desde SQL.
CREATE FUNCTION actualizar_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;
CREATE TRIGGER municipio_updated BEFORE UPDATE ON municipio FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER categoria_updated BEFORE UPDATE ON categoria FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER comercio_updated BEFORE UPDATE ON comercio FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
