CREATE TABLE solicitud_comercio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_negocio VARCHAR(160) NOT NULL,
    persona_contacto VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    whatsapp VARCHAR(30),
    categoria VARCHAR(120) NOT NULL,
    direccion VARCHAR(300) NOT NULL,
    descripcion VARCHAR(2000) NOT NULL,
    web VARCHAR(2000),
    instagram VARCHAR(2000),
    observaciones VARCHAR(2000),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    consentimiento_privacidad BOOLEAN NOT NULL CHECK (consentimiento_privacidad),
    version_privacidad VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER solicitud_comercio_updated BEFORE UPDATE ON solicitud_comercio
    FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TABLE solicitud_publicidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_negocio VARCHAR(160) NOT NULL,
    persona_contacto VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    tipo_interes VARCHAR(40) NOT NULL,
    mensaje VARCHAR(2000) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    consentimiento_privacidad BOOLEAN NOT NULL CHECK (consentimiento_privacidad),
    version_privacidad VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER solicitud_publicidad_updated BEFORE UPDATE ON solicitud_publicidad
    FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
